version: '3.9'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@10.12.40.23:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: